name: CI
on: [push]
jobs:
  test-example:
    name: test example
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # os: [macos-latest, windows-latest, ubuntu-latest]
        os: [ubuntu-latest]
    steps:
      - run: echo "${{ github.actor }}"
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn' # https://github.com/actions/setup-node/blob/main/docs/advanced-usage.md#caching-packages-dependencies  
      - run: yarn --frozen-lockfile
      - run: yarn workspace example test:nowatch

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: [test-example]
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Setup Node.js 16.x
        uses: actions/setup-node@v3
        with: 
          node-version: 16
          cache: 'yarn'

      - name: Install Dependencies
        run: yarn --frozen-lockfile 

      - name: Create Release Pull Request
        uses: changesets/action@v1
        with:
          publish: yarn changesets-publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}